apiVersion: v1
kind: Secret
metadata:
  name: local-ca
  namespace: cert-manager
type: kubernetes.io/tls
stringData:
  # the data is abbreviated in this example
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIF1zCCA7+gAwIBAgIUAYLpwsMeE1+EWzu9l0y2p3htcmEwDQYJKoZIhvcNAQEN
    BQAwezELMAkGA1UEBhMCVVMxEjAQBgNVBAgMCU1pbm5lc290YTEUMBIGA1UEBwwL
    ......
    -----END CERTIFICATE-----
    
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKgIBAAKCAgEAxV6WvXi5Lhxky3Fm5Rq3JWEgbCJke0Z9YbIZKJ0o6/A9U//R
    iaa4ewzspQa3qEADgjvkF3stEk166QdxAimote8zoXgk6pjHlOZoJzYObcsKx8tR
    ......
    -----END RSA PRIVATE KEY-----
