apiVersion: v1
kind: Secret
metadata:
  name: svc-tmcsm-user-trusted-ca-secret
  namespace: tmc
data:
  # Double base64 encoded value of harbor ca.crt.  Name harbor-ca used in trust section of TKG cluster spec
  harbor-ca: TFMwdExTMUNSVWRKVGlCRFJ......
  ldap-ca: TFMwdExTMUNSVWRKVGlCRFJWS......
type: Opaque

