apiVersion: run.tanzu.vmware.com/v1alpha3
kind: KappControllerConfig
metadata:
  name: svc-tmcsm-kapp-controller-package
  namespace: tmc
spec:
  kappController:
    config:
      caCerts: |
        -----BEGIN CERTIFICATE-----
        MIIDsTCCApmgAwIBAgIUHSJbswh0vDbKanIIkUwJPvzqv2swDQYJKoZIhvcNAQEL
        BQAwaDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1OMRQwEgYDVQQHDAtNaW5uZWFw
        b2xpczERMA8GA1UECgwIdmRvdWJsZWIxDDAKBgNVBAsMA2xhYjEVMBMGA1UEAwwM
        ......
        -----END CERTIFICATE-----
    createNamespace: false
    deployment:
      apiPort: 10100
      concurrency: 4
      hostNetwork: true
      metricsBindAddress: "0"
      priorityClassName: system-cluster-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
    globalNamespace: tkg-system
  namespace: tkg-system
