apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: svc-tmcsm
  namespace: tmc
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.25.7---vmware.3-fips.1-tkg.1
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 3
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    variables:
      - name: vmClass
        value: tmc-vm
      - name: storageClass
        value: vsan-default-storage-policy
      - name: defaultStorageClass
        value: vsan-default-storage-policy
      - name: trust
        value:
          additionalTrustedCAs:
          - name: harbor-ca
      - name: nodePoolVolumes
        value:
        - name: containerd
          capacity:
            storage: 20Gi
          mountPath: /var/lib/containerd
          storageClass: vsan-default-storage-policy
        - name: kubelet
          capacity:
            storage: 20Gi
          mountPath: /var/lib/kubelet
          storageClass: vsan-default-storage-policy
      - name: controlPlaneVolumes
        value:
        - name: containerd
          capacity:
            storage: 20Gi
          mountPath: /var/lib/containerd
          storageClass: vsan-default-storage-policy
        - name: kubelet
          capacity:
            storage: 20Gi
          mountPath: /var/lib/kubelet
          storageClass: vsan-default-storage-policy
      - name: clusterEncryptionConfigYaml
        value: |
          apiVersion: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          resources:
            - resources:
                - secrets
              providers:
                - aescbc:
                    keys:
                      - name: key1
                        secret: QiMgJGYXudtljldVyl+AnXQQlk7r9iUXBfVKqdEfKm8=
                - identity: {}
