harborProject: "harbor.vdoubleb.com/tmcsm"
dnsZone: "tmc.vdoubleb.com"
postgres:
  userPassword: "VMware123!"
  maxConnections: 300
minio:
  username: admin
  password: "VMware123!"
contourEnvoy:
  serviceType: LoadBalancer
authenticationType: ldap
oidc:
  issuerType: pinniped
  issuerURL: https://pinniped-supervisor.tmc.vdoubleb.com/provider/pinniped
idpGroupRoles:
  admin: tmc-admin
  member: tmc-members
ldap:
  type: "activedirectory"
  host: "w2k16-wdc2.vdoubleb.com"
  username: "CN=pinniped,CN=Users,DC=vdoubleb,DC=com"
  password: "VMware123!"
  domainName: "activedirectory-ldap"
  userBaseDN: "CN=Users,DC=vdoubleb,DC=com"
  userSearchFilter: "(&(objectClass=person)(sAMAccountName={}))"
  groupBaseDN: "OU=Groups,DC=vdoubleb,DC=com"
  groupSearchFilter: "(&(objectClass=group)(member={}))"
  rootCA: |
    -----BEGIN CERTIFICATE-----
    MIIDYzCCAkugAwIBAgIQVJnvTnb8nopOE/YisbxfMzANBgkqhkiG9w0BAQsFADBE
    MRMwEQYKCZImiZPyLGQBGRYDY29tMRgwFgYKCZImiZPyLGQBGRYIdmRvdWJsZWIx
    EzARBgNVBAMTClcySzE2LVdEQzIwHhcNMjQwMjA1MTcwMzA2WhcNMjkwMjA1MTcx
    MzA1WjBEMRMwEQYKCZImiZPyLGQBGRYDY29tMRgwFgYKCZImiZPyLGQBGRYIdmRv
    dWJsZWIxEzARBgNVBAMTClcySzE2LVdEQzIwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQDRc00duUHdSOqU4AgT3jcRrtbOBt2f9ZhitOOJu40AjAYwxUbl
    pt2pQReMd9fyTphWNuc/oVQpzXdQd7GC1JXODrgCaDXWBXeGM82qD/qboSkeGahO
    zAy6bn+JKkPPxo8TnUPZfgHClxVHRXrXozXV2oaG8RvRUCuX3lNHR8lM2AJGXRbM
    M/pR+JHv6kecS1iSz5Cm3+HSsqQK83PrAi/vQnvEjl6n6npApp7642Kw5HEr07FL
    LnYEuB5micdAaGMKhQtQLb+zP52EQQPFoneEanDREmyUsvw/wdXA9c1epBsQpSed
    eNS4qPxagsTPHK4q25Tg1NlDNebYaxCWOshfAgMBAAGjUTBPMAsGA1UdDwQEAwIB
    hjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTeodGxc4T0LBd5DmMBrcqm9bzW
    XjAQBgkrBgEEAYI3FQEEAwIBADANBgkqhkiG9w0BAQsFAAOCAQEAxMFqsW2L2zep
    0YNl6W+Y3qf9Sgxg2A61+AIsvcRUKbpIcVtp+5ghMwH2frLllT06ah67mrlgDMGj
    y1U0CMU5KpiU7NShyLsJafG2QSyHgUFMMVqQMvJNZLJ8ntP8nGxdzqyGCGv7X6Wg
    YWiK9JQxHbr7qwnTIibEIrQzyTTb3oS9goiYLppakeXJ8Nru22ppSGoDXORZQOqI
    MvMZAcu0SIHUyH8ssjn80kJcmmqyyQv95CqFSX/uMgtNFgrkJdYFV0r0WZZ2y0OH
    2GPfmAWWCrctj/+2IqQ2ZZBAucnrxmkA1TUg3ECbsWx7Pd76F4jnyRD8h0UkYW36
    xdEQGfDKmA==
    -----END CERTIFICATE-----
certificateImport: true
trustedCAs:
  # idp-ca certifcate needed if idp signed by private ca
  ldap-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDYzCCAkugAwIBAgIQVJnvTnb8nopOE/YisbxfMzANBgkqhkiG9w0BAQsFADBE
    MRMwEQYKCZImiZPyLGQBGRYDY29tMRgwFgYKCZImiZPyLGQBGRYIdmRvdWJsZWIx
    EzARBgNVBAMTClcySzE2LVdEQzIwHhcNMjQwMjA1MTcwMzA2WhcNMjkwMjA1MTcx
    MzA1WjBEMRMwEQYKCZImiZPyLGQBGRYDY29tMRgwFgYKCZImiZPyLGQBGRYIdmRv
    dWJsZWIxEzARBgNVBAMTClcySzE2LVdEQzIwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQDRc00duUHdSOqU4AgT3jcRrtbOBt2f9ZhitOOJu40AjAYwxUbl
    pt2pQReMd9fyTphWNuc/oVQpzXdQd7GC1JXODrgCaDXWBXeGM82qD/qboSkeGahO
    zAy6bn+JKkPPxo8TnUPZfgHClxVHRXrXozXV2oaG8RvRUCuX3lNHR8lM2AJGXRbM
    M/pR+JHv6kecS1iSz5Cm3+HSsqQK83PrAi/vQnvEjl6n6npApp7642Kw5HEr07FL
    LnYEuB5micdAaGMKhQtQLb+zP52EQQPFoneEanDREmyUsvw/wdXA9c1epBsQpSed
    eNS4qPxagsTPHK4q25Tg1NlDNebYaxCWOshfAgMBAAGjUTBPMAsGA1UdDwQEAwIB
    hjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTeodGxc4T0LBd5DmMBrcqm9bzW
    XjAQBgkrBgEEAYI3FQEEAwIBADANBgkqhkiG9w0BAQsFAAOCAQEAxMFqsW2L2zep
    0YNl6W+Y3qf9Sgxg2A61+AIsvcRUKbpIcVtp+5ghMwH2frLllT06ah67mrlgDMGj
    y1U0CMU5KpiU7NShyLsJafG2QSyHgUFMMVqQMvJNZLJ8ntP8nGxdzqyGCGv7X6Wg
    YWiK9JQxHbr7qwnTIibEIrQzyTTb3oS9goiYLppakeXJ8Nru22ppSGoDXORZQOqI
    MvMZAcu0SIHUyH8ssjn80kJcmmqyyQv95CqFSX/uMgtNFgrkJdYFV0r0WZZ2y0OH
    2GPfmAWWCrctj/+2IqQ2ZZBAucnrxmkA1TUg3ECbsWx7Pd76F4jnyRD8h0UkYW36
    xdEQGfDKmA==
    -----END CERTIFICATE-----
  # harbor-ca certifcate needed if harbor signed by private ca
  harbor-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIUHSJbswh0vDbKanIIkUwJPvzqv2swDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1OMRQwEgYDVQQHDAtNaW5uZWFw
    b2xpczERMA8GA1UECgwIdmRvdWJsZWIxDDAKBgNVBAsMA2xhYjEVMBMGA1UEAwwM
    dmRvdWJsZWIuY29tMB4XDTI0MDIwNTA0MDI0NVoXDTI5MDIwMzA0MDI0NVowaDEL
    MAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1OMRQwEgYDVQQHDAtNaW5uZWFwb2xpczER
    MA8GA1UECgwIdmRvdWJsZWIxDDAKBgNVBAsMA2xhYjEVMBMGA1UEAwwMdmRvdWJs
    ZWIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0hMvbnnT77x8
    Bs7mWkXmQE/LgXfUyOFm4cN50Nlg+XeFjKwZu0UzAB6ZOqcWUh1zh9i5IdNP6+ga
    OkUlLastLQoLB7GGIrDMvHQ+Gam3CcmHGK4XKQdAclwduSdpdFj2glodPvZAH5ut
    KUiMbj8jIj0l8FmfgUNKjj3auBCcC9vr8tnFOLCw31v2z1szanF2Ru9L5ol6HBaA
    AUOiKEimZqq5gX8pjp7WoS05L3i84rDLQS1mcg9y2ftBo9Dhht9G7XMDMRSkz/Jh
    nIhLajVNlBxh8bRjU3Lef0twAR6ZPkg+bxJvhBlyZu2nT614kGBkvrQR+DvdFACg
    i+nu2ickCwIDAQABo1MwUTAdBgNVHQ4EFgQUY2++/AMqPqCBUDdyxkAOA/fmjIUw
    HwYDVR0jBBgwFoAUY2++/AMqPqCBUDdyxkAOA/fmjIUwDwYDVR0TAQH/BAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEAiRLiWbcdTVS9QKRaiCmo1dWrWOseghjthe7h
    bibllikx1pYJJBBPi4NfkKh51Dr44NWXIFsEW3GrsoNWw62ksiJMPMcRaeMROY2z
    Ud+0uz/6key6wuIaGkow7Jg0XyQJgVkfO+b/5o9Fi5vPRbPY8FCnxOUC0UbGP4uv
    0v2KMnStG78vqxO/tad2dquBmvZldKN6R/PP9y4yqxR5KmZlFjYNrWmOEnfeJeTB
    /O/w+rsPpIH0iHhBjmulVM+wtQFM2FxzyRLfmb4+pvvRTQzgs0HGcgQ8m/NnVOQW
    txWFoMOuX+nWVPcZkZpGe7cJwAFzin6HZj03jtU6y8JZDk3zuQ==
    -----END CERTIFICATE-----
#alertmanager: # needed only if you want to turn on alerting
#  criticalAlertReceiver:
#    slack_configs:
#    - send_resolved: false
#      api_url: https://hooks.slack.com/services/...
#      channel: '#<slack-channel-name>'
telemetry:
  ceipOptIn: false
  eanNumber: ean-not-specified
  ceipAgreement: false
size: small